[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "08d68e7a9a20fd504868dbf9939acb03e42cd6f2"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "33ed81d40eaa5eda2ce9b610b17c270d71b502c55f70d6e731c31f9c41865b2b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "08d68e7a9a20fd504868dbf9939acb03e42cd6f2"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "33ed81d40eaa5eda2ce9b610b17c270d71b502c55f70d6e731c31f9c41865b2b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "08d68e7a9a20fd504868dbf9939acb03e42cd6f2"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "33ed81d40eaa5eda2ce9b610b17c270d71b502c55f70d6e731c31f9c41865b2b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc8afd5ac45593aa86ed3efdc933c55a2265d904"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "041912a0ab4bb0ad35bc2081bd363ddf22cc2c32bdca93d47b88729dfe6c83c2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.aarch64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc8afd5ac45593aa86ed3efdc933c55a2265d904"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "041912a0ab4bb0ad35bc2081bd363ddf22cc2c32bdca93d47b88729dfe6c83c2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.aarch64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc8afd5ac45593aa86ed3efdc933c55a2265d904"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "041912a0ab4bb0ad35bc2081bd363ddf22cc2c32bdca93d47b88729dfe6c83c2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.aarch64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63847cfb285557fffa80ad20a0ce0945b4e287cd"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "13ddea719db5f14f3e9e1f7e817542c9065b2f344be20339bbd855c38fa22b70"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63847cfb285557fffa80ad20a0ce0945b4e287cd"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "13ddea719db5f14f3e9e1f7e817542c9065b2f344be20339bbd855c38fa22b70"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63847cfb285557fffa80ad20a0ce0945b4e287cd"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "13ddea719db5f14f3e9e1f7e817542c9065b2f344be20339bbd855c38fa22b70"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4428ef11a0191c830063f9d06b4ba7a360999b69"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0aa95a1269cbdd0f93ff953c51a14dea4c6d641be56a062b7618e791ae6e1a50"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.armv6l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4428ef11a0191c830063f9d06b4ba7a360999b69"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0aa95a1269cbdd0f93ff953c51a14dea4c6d641be56a062b7618e791ae6e1a50"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.armv6l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c6e30c96c969f637f4c5bb6eb5f6a2283557a21"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "d30882fd90fc4b62f8d54ee46c8c2bfddb30a8c9329b3f281a9284fd5cc81d4e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.armv6l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c6e30c96c969f637f4c5bb6eb5f6a2283557a21"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "d30882fd90fc4b62f8d54ee46c8c2bfddb30a8c9329b3f281a9284fd5cc81d4e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.armv6l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "022bb00783850db79e0aa766b5fbe0ff671b84bf"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "6a3801439228ce3dbf6068b838b5bc3b13c68c8a10ba3f5dadf169300b5bb9c1"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.armv7l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "022bb00783850db79e0aa766b5fbe0ff671b84bf"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "6a3801439228ce3dbf6068b838b5bc3b13c68c8a10ba3f5dadf169300b5bb9c1"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.armv7l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "022bb00783850db79e0aa766b5fbe0ff671b84bf"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "6a3801439228ce3dbf6068b838b5bc3b13c68c8a10ba3f5dadf169300b5bb9c1"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.armv7l-linux-gnueabihf-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfa80cd4d0c460cad3cf27a752294081f75486f3"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fedb0c10dc62dea88f4108f9fcb906dc4bc5da1f696e589c81315438c208249a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.armv7l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfa80cd4d0c460cad3cf27a752294081f75486f3"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fedb0c10dc62dea88f4108f9fcb906dc4bc5da1f696e589c81315438c208249a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.armv7l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfa80cd4d0c460cad3cf27a752294081f75486f3"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fedb0c10dc62dea88f4108f9fcb906dc4bc5da1f696e589c81315438c208249a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.armv7l-linux-gnueabihf-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0263c6d0e03530e6ce25c56bc1ec6e578e2c3a7b"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fab09ce4ee431e68896fd7916dea62e8bf7178a6cbad9833d187c140a525391a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.i686-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0263c6d0e03530e6ce25c56bc1ec6e578e2c3a7b"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fab09ce4ee431e68896fd7916dea62e8bf7178a6cbad9833d187c140a525391a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.i686-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0263c6d0e03530e6ce25c56bc1ec6e578e2c3a7b"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fab09ce4ee431e68896fd7916dea62e8bf7178a6cbad9833d187c140a525391a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.i686-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc8f1ac03e824dd3895420dc5ab2b45bd44b2d96"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "65bb43178047f2d4828140575a3932b439417bf3af3a81be04e4490af4a97e29"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.i686-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc8f1ac03e824dd3895420dc5ab2b45bd44b2d96"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "65bb43178047f2d4828140575a3932b439417bf3af3a81be04e4490af4a97e29"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.i686-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc8f1ac03e824dd3895420dc5ab2b45bd44b2d96"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "65bb43178047f2d4828140575a3932b439417bf3af3a81be04e4490af4a97e29"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.i686-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f846f1abe51d227cca23a6a4c1006a3c8541898"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "d3d427a46c414520fdae3182120200987439fd26f4e5ab1f011c29c96b7d7040"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.i686-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8328b165fd07eac71f0bd29ec0144f12df676f97"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "1aeb78d5f53476e00968a94f644ba25faecc4cf0216d525b5161839ff546c0e1"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.i686-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4f979df177d856d68c0ae9085f2e983b922b498"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1097d157ac9f7990c18dbf5abb46448890f3559e57e84febddf47ad284ea7091"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.powerpc64le-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4f979df177d856d68c0ae9085f2e983b922b498"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1097d157ac9f7990c18dbf5abb46448890f3559e57e84febddf47ad284ea7091"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.powerpc64le-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4f979df177d856d68c0ae9085f2e983b922b498"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1097d157ac9f7990c18dbf5abb46448890f3559e57e84febddf47ad284ea7091"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.powerpc64le-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "080ea50695dd386fbf48eeae9be384cdeb4270b0"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ec0b2799231586bc9b379b3b21f6b9de831e3c708e99559c5f212ee8e121b8d7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "080ea50695dd386fbf48eeae9be384cdeb4270b0"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ec0b2799231586bc9b379b3b21f6b9de831e3c708e99559c5f212ee8e121b8d7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "080ea50695dd386fbf48eeae9be384cdeb4270b0"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ec0b2799231586bc9b379b3b21f6b9de831e3c708e99559c5f212ee8e121b8d7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "33bd201c530e879248a91bdcdf664d1ae318fee5"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "00e9e1ab65ad1f6b2b1d1a28d86b5be6a94307154e149a980307d22f0ea49e02"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "33bd201c530e879248a91bdcdf664d1ae318fee5"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "00e9e1ab65ad1f6b2b1d1a28d86b5be6a94307154e149a980307d22f0ea49e02"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "33bd201c530e879248a91bdcdf664d1ae318fee5"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "00e9e1ab65ad1f6b2b1d1a28d86b5be6a94307154e149a980307d22f0ea49e02"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a4085c4e7a333f3ca7cb799ce84aa0d7ae1975b"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "686870bc16b29ef7c4df2f6709eb3ae597652904160d878d79819d20d5dab919"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.x86_64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a4085c4e7a333f3ca7cb799ce84aa0d7ae1975b"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "686870bc16b29ef7c4df2f6709eb3ae597652904160d878d79819d20d5dab919"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.x86_64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a4085c4e7a333f3ca7cb799ce84aa0d7ae1975b"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "686870bc16b29ef7c4df2f6709eb3ae597652904160d878d79819d20d5dab919"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.x86_64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ef9527fc1fd3d37305503d5e05cfc55f19c069e"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8527ecc6adccdc8906b9ff68873e2b91e58c4de8402291f9532ee6a14f1cafd7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ef9527fc1fd3d37305503d5e05cfc55f19c069e"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8527ecc6adccdc8906b9ff68873e2b91e58c4de8402291f9532ee6a14f1cafd7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ef9527fc1fd3d37305503d5e05cfc55f19c069e"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8527ecc6adccdc8906b9ff68873e2b91e58c4de8402291f9532ee6a14f1cafd7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f120489ea3d55fa40ead312361a5c73459ff4dd"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "d90559322346b555d16ad85df4fd9ef91b225aa685a45aff82a865a724e5cc9c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.x86_64-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e639918e2827f3ffa7001482c5c555f1ba19bfc1"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "ece6b07cd7c55a9720b41470df6323998cfcb5da8942c4c7b496d5c5fbfbfacc"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.0+1/LAMMPS.v2.3.0.x86_64-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
