[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d573be4e0a220636c246281b18cc4a840d7b899"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0a27980d887d2a928e57ab1defac86553216505f3c00c77fd731976ad4bfbd00"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.aarch64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a9f6119db7905ecc23b126a71b78ffa17fc667a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "5a8ea28235c8ae600059b1b06776c71d756cd81176a1b688af6556ff7df3c105"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.aarch64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78bc6b198ab385867a32ab07ac358a5619925718"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "578ec2cadd8c167477c7936721d0a92d9fb42fea71d64e5eaefa81b0ff4e7e8b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.aarch64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c33f49bf7e043866256ad83615c2f595349ab17"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "27a69b621b1464bd3526308b713c31f3cae53809e79fbc6234f0b7c6450ce288"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c7320fe97bbc0aa2bc1a1ef54a978209b6a1320"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "d8204cdf92f54fe996b67ecf78801e615b12f58e3245665d22f0ecbd864ab1d7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.armv7l-linux-gnueabihf-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b79290c3ed77de59abf3bb3e96884c62f481531e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "85907764af05096e988459c110c04c458fb00e1972066914582d62d38fb12b09"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.armv7l-linux-gnueabihf-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2dc077b469126fd2925f1c0b17c185094a03064b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "72b6e4811649cb6f02ee38db6a95eb270fa73ba1ad939bbe71d0de71195ab4ea"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.armv7l-linux-gnueabihf-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5bc1421f57d16292d46ada07f3d0feba90c5ad3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "10b34a6d0b3070992954c9c29d80401e682638b070b60eafc667d8f655c8791a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e16023d9833bec4de37b045e28f85a7f4d964347"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "6c28267ab432b0b7a68e09a75e880beba2f91b84e303d782ebd5c66b1c9416a9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.i686-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a640b950d8fd627865a87962a59ab9856afd3e8b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "d684ff3559563efa834945b02f7d0fed8b942a3425801625edeaff5837d4382c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.i686-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ea50367ca9f7ce694e5dcb6ef66502cb3f23398"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "e693ececa56130ff75b36637fe59d3a33c795b81910569c13d197332805697d0"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.i686-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f16a64f6c472808b7e8bce70eb61787c1989cdd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1102ebb95bdb361bcb5c618c9394a8e366ca4485a448c1653dfa6749516ef1ac"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa0a54c5000413edf731a29f99194c3cfeb132f6"
libgfortran_version = "4.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "f8eb4ac2f6af606f26c3c1be71fef022816448f108f8fa5db79226633fe0f47e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.i686-w64-mingw32-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "199a1c4e2a7c9a4a68a9de3d19278a663473c7d2"
libgfortran_version = "4.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "b6e8ab9de487fd9548db0b0d8fcb4bd999a8b10541043ea158d02680fd3e4c8d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.i686-w64-mingw32-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4d62588c6fdf6dcfb65ca8fccd543d409972de5"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "85f09b08435b7b73fb52603607322994b8b10b94cdd4c646881dce6d59a61f5c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.i686-w64-mingw32-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d06fee113d8f2672371444c959879e52fba4d2a"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "ebf03e907b9575cb47c9a474849a32d38d0cb23e65faeeac15110be2be278253"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52b97ccf036e7e49cd09d320f442abb68402dab9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8c5ae70352ff10f93c9e8bf000342f2e539538167609d4293fc3011c460aca63"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.powerpc64le-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f775359b84dd7d5812baefe7a8426f70f12cb5d4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fc1c372b1928e78b9eb3a10aa6c58ab028419bcd7b85e4a311f456d8c7703dfa"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.powerpc64le-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "476495ec87cd3002d71d5361da9a741549a82ea8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "365222ba04f28f0b4ebbcb437abd6314eac46b68e6380d2291b3ee5e7fa8fb93"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.powerpc64le-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a3ca7eac419ce40ad44e1330a2df85c9cb90c2e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "85ae263acf55d966590fdd3d6a132a4d3e4b5a6acc832393695c302b2e2223f6"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "0cc60b0211999c689bee43e342179bd9a5a7d3c3"
libgfortran_version = "4.0.0"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "b85bcc4a535c8cf83f88c0339515e2b7aa348f4f6ea7ef485532c7229d01b1ab"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "e610c5fd5ace61028034f83be3e7d2e2aed79748"
libgfortran_version = "5.0.0"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "d32786adcbc40e535474b25fface80ef6ce53e4cf9e2c070830eedc6e84987fd"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccf8f7b0dbd67656cd1239089671a8ed5bec9c0a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b65c73c27efdc90a19491def60feef79d60b04a685c607b745bc39ebc39a51a3"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.x86_64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4839937a71b654d0d4b23ab2f853396a9042bac4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "15fcb77cf22c93d3edacb9797aa0a8bab5ebe2d84d05552c5829aacbd788b808"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b22bcaefb448ee9ca9baf128b3c88a620818f82"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "24da030f2516b4025312d8c8516377b5adee02393077f3e54f2b60e134a1f260"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.x86_64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "161c05c3e7eaf20052dd26bd2f845bb3084807d8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7998dc1675e985a7cf253b938e58e8626e3cc76c762fb1f4b4efa08730ee62fa"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13b9cd1d08e18507f5c9c1548fa7c2472718dc3e"
libgfortran_version = "4.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "fea46ee768d4427d789f8ec5c4129d26c391fabad5d0ebfb57d188e771000c5d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.x86_64-w64-mingw32-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9682bb8ea5c3b23b84c56d26f3f124e3fc583a7d"
libgfortran_version = "4.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "45ceebe075892353fec95a1b3ae3e6cee546a4e91c51bfe218b7ecccd83551fb"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.x86_64-w64-mingw32-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2af93b62731d94e3c18874cbcf1f8f4cf716b14e"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "8404b512ac5b804ebb56b9e6930a8e6aa1bdfc0f0b3f4b0f93fbc108e4d1855a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.x86_64-w64-mingw32-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b11334fbe8d7286efee752448c4ba01c5a34851d"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "560f423f0f1b510eef30cb9404543fede8098dc2c0fb6afab2ab351d814201ab"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+0/LAMMPS.v1.0.1.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
