[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "382567a4a3e9154e8ddf15e377e35181df6e77bd"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "eaa08ae2626383b665cf3b759e643039915cf98e019cadf1d3f8fabb3e772fb5"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.aarch64-apple-darwin.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66c4d099f9ff8d837fb0295df5515343dfd13f7a"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "00824fc3253f007768ab6711d37c3262a5bdcc0e8deca5b17daf421c18d650ad"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c7905fd9fb58dc5fd6a714f0ec5d35e4a86d422"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fd6571c0631d8e95efe3eb4cd32babf006b7ce915e6834ac31ca1ec9d7d9aaaf"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b03e1afa1086ad0a9f90f86637b98dbbbf8e09d5"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "da5fc0cbdc8f19f104328d2e1d27a43bc081d224b9eb8180f9810f9218caee49"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db683f430ab4c36a6d67bbad80a7eee8d5519067"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b685c0560cf944d20b6bb066f783e65376f12b0f84243eff672ee4d66ff6bd5c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8782b71a78000d16ab86e3e67f5632e71b165ad4"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "3da05049af0a6be5eea505700afd3037ff64614e6613941263cb991c45497455"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ed395c63b4b9d9c062887d7a736c3746c0ec3b6"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "344bc212336b9bfe30deb3aac5962bd984770a0353aa96d4b0d3cd050842371b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d6cb7aa779987ce02f27d1b34d54e68af193754"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "5ad97e2118827a685baa1580e3f69234c3ec8bac8ea60dec4572e20f06bd5d0a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.i686-linux-gnu-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74dc55116d58842ea6747fce0882b39360cd1e0b"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "908d1b5ad5e5a7f26134865c6130bb1bec61e3a2781a842ebc4c718dc1b04d50"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.i686-linux-gnu-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64a66c15a8231bfb4ea34819a7e69b713440fb8b"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "5bf27acbab4127d52f9da91a93925015fcf1ad7fc288f2683b55977734327561"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab05deb1cac83b4f40f1573fe4b130f783fc8c02"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "bc3f3d240f32bc8adf603d44edb9a4bed3a6fc83e3ccf371e2488b6f24b60f07"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "537f14e7d6aba3fd505c7bf4dfe2dbcea6aa61ef"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "e0e18e34a4f7b9958f6a45e5a0fdc5ab41c096800f6fbbf5b923a8034aa13946"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f822ee74cb29f771b12a5374e7b8f2c708799035"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "32adb7af743d32a8b77dc142e984e1e91d349fdd7232705adb262276dbee073b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "b18a8b3b450cb18850d7496e2579f3e456f94864"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "e47b1d7a18b7fe0aa18c3ba057a082a928256e63c06b35feaff18e01b9b6eaa9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.x86_64-apple-darwin.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a7da0e259998f622ffe77dd00d17da858c70f2c"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "9ef6807c552b21dc7def81091355bbf7861d4aafdc04663e65de805570b40a27"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "871369d57f85f8b623dac42a2c0c42ed43f5f411"
libc = "glibc"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "f11290435970b0d2a72a6ae9f0e926269d33190d52fd54bedd11097238998b13"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "bf6da9cd569587aede933b051b68631d86efc965"
os = "freebsd"

    [[LAMMPS.download]]
    sha256 = "37a816369e052df561cdbbd6e3dd0d673776729268dc9e1429ed603aaf816535"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2d80cd5f69954487e9794d6a75c43f1cf390e91"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "89b885bda0419ca489a3fe2bb98c280a5b694e1f38d9e8f8d5d4c4a1adb5f491"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfa92b9e583cf3a34d0d6f91dd81502a3dda77a5"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "2fd39e7bc212508b53b48dd56f846edebe0e7e4534f96b97de13f95cd103e727"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.0+0/LAMMPS.v1.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
