[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "128bac4bef1961d6fb8263529584bf0e485044aa"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "0209f07a7b52152b22020e740ae36ee44371144cd6690efeb045042e3db5f4c8"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "128bac4bef1961d6fb8263529584bf0e485044aa"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "0209f07a7b52152b22020e740ae36ee44371144cd6690efeb045042e3db5f4c8"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "128bac4bef1961d6fb8263529584bf0e485044aa"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "0209f07a7b52152b22020e740ae36ee44371144cd6690efeb045042e3db5f4c8"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5170393b202f8d32182785dc3c7455d99c3814ff"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "998a3c6d68641cd3a81f893f6c8ae6dfaf4328aee7f55935735d44a3eab7b62f"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.aarch64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5170393b202f8d32182785dc3c7455d99c3814ff"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "998a3c6d68641cd3a81f893f6c8ae6dfaf4328aee7f55935735d44a3eab7b62f"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.aarch64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5170393b202f8d32182785dc3c7455d99c3814ff"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "998a3c6d68641cd3a81f893f6c8ae6dfaf4328aee7f55935735d44a3eab7b62f"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.aarch64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27a076fdd09a57d0d757bb1678ab540f6fb81359"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "011b56f50e4a13db125ebe02dedc135c5779442fb494324af35a9c244adb8eb4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27a076fdd09a57d0d757bb1678ab540f6fb81359"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "011b56f50e4a13db125ebe02dedc135c5779442fb494324af35a9c244adb8eb4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27a076fdd09a57d0d757bb1678ab540f6fb81359"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "011b56f50e4a13db125ebe02dedc135c5779442fb494324af35a9c244adb8eb4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3469b9a18543b3c886a9d1eb7490896629368e9"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "6d89d4ebb37c441395234b6993e4e0a96013d563e3fd2d7c604a91d53759dede"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.armv6l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3469b9a18543b3c886a9d1eb7490896629368e9"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "6d89d4ebb37c441395234b6993e4e0a96013d563e3fd2d7c604a91d53759dede"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.armv6l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c59d8c94b561e9ff091086db29608e1a63595a5a"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ddb498d1d5984f06d5f5e2b0a4af5780334261c0984c92885b0ca30786e0bba9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.armv6l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c59d8c94b561e9ff091086db29608e1a63595a5a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ddb498d1d5984f06d5f5e2b0a4af5780334261c0984c92885b0ca30786e0bba9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.armv6l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94db6d3a3e433060f80cf07ecd9122a690ea84fc"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "a78e0974c4a9acf375cde5affbe9641db7b489c49ebc14d1f63945012cdae0f0"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.armv7l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94db6d3a3e433060f80cf07ecd9122a690ea84fc"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "a78e0974c4a9acf375cde5affbe9641db7b489c49ebc14d1f63945012cdae0f0"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.armv7l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94db6d3a3e433060f80cf07ecd9122a690ea84fc"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "a78e0974c4a9acf375cde5affbe9641db7b489c49ebc14d1f63945012cdae0f0"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.armv7l-linux-gnueabihf-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cee551172f1402d738220d2bb6cea27ea76d6fc"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "f13c5143d0f8fd33ed0fd2aaa877444209760d5ef8fbf56dc6b271408b124c01"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.armv7l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cee551172f1402d738220d2bb6cea27ea76d6fc"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "f13c5143d0f8fd33ed0fd2aaa877444209760d5ef8fbf56dc6b271408b124c01"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.armv7l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cee551172f1402d738220d2bb6cea27ea76d6fc"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "f13c5143d0f8fd33ed0fd2aaa877444209760d5ef8fbf56dc6b271408b124c01"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.armv7l-linux-gnueabihf-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d909dd9026f65a07b235d6dbbcd6d3c24343edd6"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "3918533a703647e87f0ba7cc697d678c2d9f2fbccc357ddbe90cc9aa4aae74e3"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.i686-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d909dd9026f65a07b235d6dbbcd6d3c24343edd6"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "3918533a703647e87f0ba7cc697d678c2d9f2fbccc357ddbe90cc9aa4aae74e3"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.i686-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d909dd9026f65a07b235d6dbbcd6d3c24343edd6"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "3918533a703647e87f0ba7cc697d678c2d9f2fbccc357ddbe90cc9aa4aae74e3"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.i686-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a04cf61f52d5ce664157cf11877596ef43ed9bf0"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fb894b635736408ee73934ed7dbc276504a6e421bead3ed25c7d0ff2586bc1e6"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.i686-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a04cf61f52d5ce664157cf11877596ef43ed9bf0"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fb894b635736408ee73934ed7dbc276504a6e421bead3ed25c7d0ff2586bc1e6"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.i686-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a04cf61f52d5ce664157cf11877596ef43ed9bf0"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fb894b635736408ee73934ed7dbc276504a6e421bead3ed25c7d0ff2586bc1e6"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.i686-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e9d0629c8cbe18db21ea37a1806c2bef3f194f0"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "2ad4c061ce32fa48f64eb0a7e85b9632b984afba9c4e97f252a281b823c76ecb"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.i686-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78fb29e63c09074f482ddc5629ab0c5074cfe328"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "40bd9cef0e586827a583e5cd4d0c9dd708e054a7efe870475b2306c3c6ce86ee"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.i686-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99fbc3578cf8ac49ab2c7020f3ab2b508955df67"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7c4e944cb090ed335841e1dfd66794c2369f0054a4f50d031f883eb19df0c48f"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.powerpc64le-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99fbc3578cf8ac49ab2c7020f3ab2b508955df67"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7c4e944cb090ed335841e1dfd66794c2369f0054a4f50d031f883eb19df0c48f"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.powerpc64le-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99fbc3578cf8ac49ab2c7020f3ab2b508955df67"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7c4e944cb090ed335841e1dfd66794c2369f0054a4f50d031f883eb19df0c48f"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.powerpc64le-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f1cdfb09321e0239145fbbbf484f31543b2db42"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "59a5553ba62fcfb59b51c0454445a014063ac6de46af3058bd383c4f7d5d38c3"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f1cdfb09321e0239145fbbbf484f31543b2db42"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "59a5553ba62fcfb59b51c0454445a014063ac6de46af3058bd383c4f7d5d38c3"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f1cdfb09321e0239145fbbbf484f31543b2db42"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "59a5553ba62fcfb59b51c0454445a014063ac6de46af3058bd383c4f7d5d38c3"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "81e434abe74d2e7f0cff8ef28d3a66b023726312"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "411856aec95767e024885f4b0132fd826e5c5d135e1a6170b6189327ec274cfe"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "81e434abe74d2e7f0cff8ef28d3a66b023726312"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "411856aec95767e024885f4b0132fd826e5c5d135e1a6170b6189327ec274cfe"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "81e434abe74d2e7f0cff8ef28d3a66b023726312"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "411856aec95767e024885f4b0132fd826e5c5d135e1a6170b6189327ec274cfe"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96e15d8fec8d7a44f4cdf317b0f78acd765b73f3"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ac090532f3d33f5181e7eff45d245d34d1d4f04efaab092f297a48b89be9d843"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.x86_64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96e15d8fec8d7a44f4cdf317b0f78acd765b73f3"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ac090532f3d33f5181e7eff45d245d34d1d4f04efaab092f297a48b89be9d843"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.x86_64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96e15d8fec8d7a44f4cdf317b0f78acd765b73f3"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ac090532f3d33f5181e7eff45d245d34d1d4f04efaab092f297a48b89be9d843"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.x86_64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64f32a083d2a9c02733ad77116a4214c9f948815"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "325502eeaca533ce579ebbd25c7e162352f3ab4eac1512fff2b1439ecb8826de"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64f32a083d2a9c02733ad77116a4214c9f948815"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "325502eeaca533ce579ebbd25c7e162352f3ab4eac1512fff2b1439ecb8826de"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64f32a083d2a9c02733ad77116a4214c9f948815"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "325502eeaca533ce579ebbd25c7e162352f3ab4eac1512fff2b1439ecb8826de"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b2c92d8a70d76def9130474085c231587bc0426"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "9fd6c016437156d94aa1681a6e759887a7cddcdc5b2dd21426629859daf8194b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.x86_64-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75e306dc1159ad33f37c73efe3eb365407354ada"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "0f9b2d965a7cb8dc639497ee9c95053403e66e0bd3ebfef6467f4c88ca19d9af"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.1+0/LAMMPS.v2.4.1.x86_64-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
