[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebac03050e759da669e763462a0e06735d7c57a8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "37b080368619540c7cc8129f693ec73cea11f6e3b66571c9c8ebe69de5ae76d9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.aarch64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fd1f46c1323d93f2b84c176a119a76a1ebf1d1b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "bb22cf55ab534e13154124ff8e5b86800b650fe0729cfe08182ce5daff13fddd"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.aarch64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d483c572a334dae13a2187cbab87aec6df73234"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "c2e10fa5c9a94bc6a9c30cc17a427b6087ab65de5c616dcd118deb26fbc566bf"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.aarch64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f4073cc4a3d9b25dbfcb31589883595eee61aa0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "da3e580e09930a805b727f104344d933d1cbfb70e35b5be8e97003229b6bdbb9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75b105a22abc890b2a2cefc3f243afd9f5e6435a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "9ecb9d1c7f15e4e0e4fc0fa7b456c6adf60a595ffe088053b69a97daf383b256"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.armv7l-linux-gnueabihf-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "582202470405af6214a2b9c1ba2401ed69d82428"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "90df159b705c26e288d49ea4c320dea473744767aa7ea82b5e58dd7330ceda0d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.armv7l-linux-gnueabihf-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18021479fc745762eac3ff68112037a905bb3788"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "5ef886c48cb4da2aa0079201907d0e28690639490315d2d692221f26b790c159"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.armv7l-linux-gnueabihf-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9ff4ab77f2e79faccdf89b8c17ed9a1fea2ddce"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "d1076410c334a02beff27da32c9873678b79ad677930fb491b8d78bba9affe3c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d57a0e358c811519138861366eb52cc8cedf1276"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "33264b3b46e432902b0a869ab63d93447497d08684c840e23a51261a639a8b6f"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.i686-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f3dd3f51d2c942059715150369ffc1e8c11120e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7e1475d364d9ce24e6d5b5862d0a142d7bfb694d449df3578ffb159b3db38288"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.i686-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8606c854964c6380909dfd319665ae7ab8c04cd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "529ac7de1ea3748b97c224693dc874665bc678daa5e21aef008ee3302b58d1d6"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.i686-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b0c23155c445ed0d10137b0eda315b0b21dfb02"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "45360b395399a8415b9cfb9c69fff3a365254d5a41df41c7f83da7946562ad54"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a68b7ac03705fad81a262eb640b4de0baf565d5"
libgfortran_version = "4.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "96750846c6c20bbda51be12be0edb17c49b229ddb84810f37dc15833a8a60b17"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.i686-w64-mingw32-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5dedbd9c0d38878e85e32266844988685a6dcc10"
libgfortran_version = "4.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "7147e65e045093684065980b3e9284c0f22a297693d3a2fb1bf283aa6ffa3104"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.i686-w64-mingw32-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b1dcafdab579b5b1e11709ef0b8722504c76532"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "86b77137490e20f47cac30124bcd9be6535ba7b3bf23b1dfc4d8791cec26413d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.i686-w64-mingw32-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20bf5b1b708a749d89524bef200c99549af9616b"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "77c52b0469b730dda77fd4568507baab9fb573e45d2ec60ead27e34080c2f21c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c9c97367afcd6a04ce5b31e9889b3a5571922e6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "47600122020b7a967913ade347bb06c1113783916afba4166a6011b8e44695e9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.powerpc64le-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c58c0bc4c755669384d186aaac89c0ca27cb772a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "41945f668e77f1c9d254d81915b5a2cf1c031a53dde6bd7824f3643260ef786d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.powerpc64le-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5db342af1571ce4db1c7560bceba9a50505f713f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "547115e5395dc98d576bae3ccc604067c65634c2c8f41f730ef88508c2f7ffb1"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.powerpc64le-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "deb48c99f9e2e74689136e23084b1d60886da2f5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "65ed4355156af06faafcdf42d6eba93ace939ae49acf8878daf8621e7996b583"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "a20a442c71404ee22b6f7d3e4edc50e3ddd70a15"
libgfortran_version = "4.0.0"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "f63103fc3a58d9384b5c7124efbcc9c1fab9753d4edd7d56c96b10850a48ff11"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "f9e29010a9b6640f7cbadf87a3e75e20aad0c528"
libgfortran_version = "5.0.0"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "6e764e8c8179fc35d03dd89e56383c3b4809ffe3fe450b28040ca352835948e6"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea7f232f5d9c8d9476f237d8fca216c963d0d3d3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "dceb5f250c5a77533d057ba5cffc25a7af98f99a4a1d4ed757a3b0bc875545d5"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.x86_64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdf349e8054e9043769ed8f0c6ee8a7051d55211"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0d6026e013903505d2b2caba9b581a13f47076d43f3503497f57fe23b4d70640"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fab3ad9b17ad1e5c15944b799cd4be744b9f0f18"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "cb9b95d19dc5547793346237d0c8e39dfafb4c72342e044399bef6f448a717b8"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.x86_64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7609f087e072b02bbae8eee88e24264a5e4bdce2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "c75fb0c7149de0d51cd573a43428368d9f1130e95cb547f3e6b30a82e8485f83"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "848c7c38a74afadad361a4284fa547bf0920cada"
libgfortran_version = "4.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "f7598c99a9977f6c29b4688baa8c09cfbbed39b1201de8994a45b6960b1240b7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.x86_64-w64-mingw32-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a8028a9002afdf0a747da3022a93eaa2d28774a"
libgfortran_version = "4.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "39142e5b6d6d18939261ae2b71beec69bc12bb561c5c2706ba8decd45c4c779f"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.x86_64-w64-mingw32-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0986e4b803d9bc24a47ed675a5ca01691232be3"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "5c0ed10c093381fefbe4653b00e5554d80083303bedfedde30f71b7ed7ca8572"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.x86_64-w64-mingw32-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c1062384c144079dab628c95602e237f3dcb611"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "263ac57b65e71445b2356288c21d7515bfc0ab803544a43332d7fd3f8d38e323"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+1/LAMMPS.v1.0.1.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
