[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "25cb068c286256baba7096b190d2d79b1c920052"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "789685cc6b50a8f5f722c1e1011e004f2fa4a4564163d0b1d679f036571c434e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "25cb068c286256baba7096b190d2d79b1c920052"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "789685cc6b50a8f5f722c1e1011e004f2fa4a4564163d0b1d679f036571c434e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "25cb068c286256baba7096b190d2d79b1c920052"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "789685cc6b50a8f5f722c1e1011e004f2fa4a4564163d0b1d679f036571c434e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bcef84c9733237d936acf0cddfe6591b2d38fff"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0c7e3bdfb9fa75d4a84cabda03898797283c830e94ad0279cea8fdba27fa4b9e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.aarch64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bcef84c9733237d936acf0cddfe6591b2d38fff"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0c7e3bdfb9fa75d4a84cabda03898797283c830e94ad0279cea8fdba27fa4b9e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.aarch64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bcef84c9733237d936acf0cddfe6591b2d38fff"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0c7e3bdfb9fa75d4a84cabda03898797283c830e94ad0279cea8fdba27fa4b9e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.aarch64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bba87e4e630b001f4600af10ff440b8a38bc5f9a"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "e3d317d1e2a379364675ca1eb9da30194f484f9d0626688f5e08263bd8dca8fa"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bba87e4e630b001f4600af10ff440b8a38bc5f9a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "e3d317d1e2a379364675ca1eb9da30194f484f9d0626688f5e08263bd8dca8fa"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bba87e4e630b001f4600af10ff440b8a38bc5f9a"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "e3d317d1e2a379364675ca1eb9da30194f484f9d0626688f5e08263bd8dca8fa"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a18f713176b5b8a259347cbb09f6f01a11a67fef"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "62c7ba980642f4e73bfb2359495245eda58032b958d463e4c06783f12943ff13"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.armv6l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a18f713176b5b8a259347cbb09f6f01a11a67fef"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "62c7ba980642f4e73bfb2359495245eda58032b958d463e4c06783f12943ff13"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.armv6l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4677063c39f81f182fc953497b44ea1bee116ffd"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "e39d3d3396e3323bc4c654cd66951bc67662be2af48a696a1e3e3e7f40619cc4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.armv6l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4677063c39f81f182fc953497b44ea1bee116ffd"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "e39d3d3396e3323bc4c654cd66951bc67662be2af48a696a1e3e3e7f40619cc4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.armv6l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbcd02137b923070cc2a0cc15f54d1c39f599d77"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "2e93eebcb917aef61a4e9410f8eed230fffda21854f88dd144671eeecceab065"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.armv7l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbcd02137b923070cc2a0cc15f54d1c39f599d77"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "2e93eebcb917aef61a4e9410f8eed230fffda21854f88dd144671eeecceab065"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.armv7l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbcd02137b923070cc2a0cc15f54d1c39f599d77"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "2e93eebcb917aef61a4e9410f8eed230fffda21854f88dd144671eeecceab065"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.armv7l-linux-gnueabihf-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b078144fda07e4e08d1ca15e3a52ac095b29dfe"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "d1c789d8329668b00c001700b478d271fd65ac168fdeea483580fc3d69a24e17"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.armv7l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b078144fda07e4e08d1ca15e3a52ac095b29dfe"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "d1c789d8329668b00c001700b478d271fd65ac168fdeea483580fc3d69a24e17"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.armv7l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b078144fda07e4e08d1ca15e3a52ac095b29dfe"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "d1c789d8329668b00c001700b478d271fd65ac168fdeea483580fc3d69a24e17"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.armv7l-linux-gnueabihf-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49a849ecd07c17c49a2a2ee5a2c2210cf4404478"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "949f66b07f5128aec7f3ec8572775119641f2f35ca0c122275c879b23554d502"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.i686-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49a849ecd07c17c49a2a2ee5a2c2210cf4404478"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "949f66b07f5128aec7f3ec8572775119641f2f35ca0c122275c879b23554d502"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.i686-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49a849ecd07c17c49a2a2ee5a2c2210cf4404478"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "949f66b07f5128aec7f3ec8572775119641f2f35ca0c122275c879b23554d502"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.i686-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe82a5c5e0f4eae8c0af48f933117e36ea257474"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1f64aade97f82ec2005b7087356f4ac4db06fcce78c97b6fa049784f710e4c7e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.i686-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe82a5c5e0f4eae8c0af48f933117e36ea257474"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1f64aade97f82ec2005b7087356f4ac4db06fcce78c97b6fa049784f710e4c7e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.i686-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe82a5c5e0f4eae8c0af48f933117e36ea257474"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1f64aade97f82ec2005b7087356f4ac4db06fcce78c97b6fa049784f710e4c7e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.i686-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5c12d6c0167ce3b7b5e8b916cfdd059161f32f6"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "6072a965586f2e92ab8b41bd263087d53b7f43c9adf9868d02074cdb534d2937"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.i686-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f2fd279740248e16113afa23f238bd3f0105ee4"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "90ed7acbee0c9c983ea926452f20ef644cfe3e08dc105b4832785dd90a780cd9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.i686-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec678e81ef3ce19648538897f228ffff2f4023fb"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7ad64af1aeea643897dda6cb097f208561f135c91b7f3290877551394f775a61"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.powerpc64le-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec678e81ef3ce19648538897f228ffff2f4023fb"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7ad64af1aeea643897dda6cb097f208561f135c91b7f3290877551394f775a61"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.powerpc64le-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec678e81ef3ce19648538897f228ffff2f4023fb"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7ad64af1aeea643897dda6cb097f208561f135c91b7f3290877551394f775a61"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.powerpc64le-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7245dec685daabc9c2551dd9ad847b9aba1cabe"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0f03515a733f8be79e0dc660f99d123672e2ac7504310babd138cd90418c78b9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7245dec685daabc9c2551dd9ad847b9aba1cabe"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0f03515a733f8be79e0dc660f99d123672e2ac7504310babd138cd90418c78b9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7245dec685daabc9c2551dd9ad847b9aba1cabe"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0f03515a733f8be79e0dc660f99d123672e2ac7504310babd138cd90418c78b9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "edbe3934f083b814eaaa3a0758c87352ad73ae68"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "05f51dfc4f4eef185fe88353b7eb9637ad43b7bf1f49184fbb07f850adb4f7f3"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "edbe3934f083b814eaaa3a0758c87352ad73ae68"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "05f51dfc4f4eef185fe88353b7eb9637ad43b7bf1f49184fbb07f850adb4f7f3"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "edbe3934f083b814eaaa3a0758c87352ad73ae68"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "05f51dfc4f4eef185fe88353b7eb9637ad43b7bf1f49184fbb07f850adb4f7f3"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95a95cfa431c4ee1919452dddb04ad8fd553cb08"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1ce5d524d0525096f8e750baa1cc55fa3b621bc5d140aba284a239da4fdc58df"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.x86_64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95a95cfa431c4ee1919452dddb04ad8fd553cb08"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1ce5d524d0525096f8e750baa1cc55fa3b621bc5d140aba284a239da4fdc58df"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.x86_64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95a95cfa431c4ee1919452dddb04ad8fd553cb08"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1ce5d524d0525096f8e750baa1cc55fa3b621bc5d140aba284a239da4fdc58df"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.x86_64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60d59d077ab4d1be5aa44576db02410292bf7a1c"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "974049d6cd6fa479db16c3c257e2a55b7873377506b56f4b44193b271a030690"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60d59d077ab4d1be5aa44576db02410292bf7a1c"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "974049d6cd6fa479db16c3c257e2a55b7873377506b56f4b44193b271a030690"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60d59d077ab4d1be5aa44576db02410292bf7a1c"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "974049d6cd6fa479db16c3c257e2a55b7873377506b56f4b44193b271a030690"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08db7be257f4e7a6b4e8fbe1bf6875b1da5cdc08"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "901619ace011b624191c7882e531b1ec0cefa06b9a4b6e93f0d4d29e46723961"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.x86_64-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8798b5faa6e75a5a302c1f5e7b98ea6e49ca3a0"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "eb76f05e218a37a92c7601bcadf6d958636a881ed138c3acf434c2721d9f5032"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.5.0+0/LAMMPS.v2.5.0.x86_64-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
