[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "73596f7c42aae8dc3fc682db7c894fe30d1fce7e"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "dba42526fe472b8513265b97f1933509879e4721712237cd224475cfda35404a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "73596f7c42aae8dc3fc682db7c894fe30d1fce7e"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "dba42526fe472b8513265b97f1933509879e4721712237cd224475cfda35404a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "73596f7c42aae8dc3fc682db7c894fe30d1fce7e"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "dba42526fe472b8513265b97f1933509879e4721712237cd224475cfda35404a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08fbcf7e6fd917e1cd0c047f6466c97a30fca9a9"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b236a936f08e49e6dd5aab3db672ac5ee3bc455f0ddb53d49d3be5bb7118b195"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.aarch64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08fbcf7e6fd917e1cd0c047f6466c97a30fca9a9"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b236a936f08e49e6dd5aab3db672ac5ee3bc455f0ddb53d49d3be5bb7118b195"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.aarch64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08fbcf7e6fd917e1cd0c047f6466c97a30fca9a9"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b236a936f08e49e6dd5aab3db672ac5ee3bc455f0ddb53d49d3be5bb7118b195"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.aarch64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d98f444b01da54db592cab4584e1c45c67d26192"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "caa7f58bb620591e0578bc50162220f9f733117702f67b770d49854773e51c18"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d98f444b01da54db592cab4584e1c45c67d26192"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "caa7f58bb620591e0578bc50162220f9f733117702f67b770d49854773e51c18"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d98f444b01da54db592cab4584e1c45c67d26192"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "caa7f58bb620591e0578bc50162220f9f733117702f67b770d49854773e51c18"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17f721cb1333e606c7fe2526b4392275eb6d18fb"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "3b8d1de846a47c98d1da4e319a7edaf246ec3019a2eed476751ad2fb755a0810"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.armv6l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17f721cb1333e606c7fe2526b4392275eb6d18fb"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "3b8d1de846a47c98d1da4e319a7edaf246ec3019a2eed476751ad2fb755a0810"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.armv6l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f558f95fa62d06b0aa371fe61e6d59ff6a88d8d7"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "cb9c349a86da3196664b31e0d9e105d7b13c15c5f01c3167884f0fdc7cb10b27"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.armv6l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f558f95fa62d06b0aa371fe61e6d59ff6a88d8d7"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "cb9c349a86da3196664b31e0d9e105d7b13c15c5f01c3167884f0fdc7cb10b27"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.armv6l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e4e9acbd364aeac4f7b85739b0f167253e28a9c"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b8c145f4eab9654c4f2e6e70d385dc4e2da9b4ee9ad5c4ec54cb1493014107a4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.armv7l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e4e9acbd364aeac4f7b85739b0f167253e28a9c"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b8c145f4eab9654c4f2e6e70d385dc4e2da9b4ee9ad5c4ec54cb1493014107a4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.armv7l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e4e9acbd364aeac4f7b85739b0f167253e28a9c"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b8c145f4eab9654c4f2e6e70d385dc4e2da9b4ee9ad5c4ec54cb1493014107a4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.armv7l-linux-gnueabihf-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1af72dda98535ce04d8cbe70a677e6272848ede5"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8400fc262a9a0f281b2ff7f43000f9a196c53cc684beb38bbda98e37f05b87a9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.armv7l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1af72dda98535ce04d8cbe70a677e6272848ede5"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8400fc262a9a0f281b2ff7f43000f9a196c53cc684beb38bbda98e37f05b87a9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.armv7l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1af72dda98535ce04d8cbe70a677e6272848ede5"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8400fc262a9a0f281b2ff7f43000f9a196c53cc684beb38bbda98e37f05b87a9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.armv7l-linux-gnueabihf-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc4f41ffb8629937d59d8b2c619626f1dbb276e3"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "656d95003a2e47f544ce9eb9f6fe9ad9823bc7e902d3a9a20d1eb0b3ae884b6c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.i686-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc4f41ffb8629937d59d8b2c619626f1dbb276e3"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "656d95003a2e47f544ce9eb9f6fe9ad9823bc7e902d3a9a20d1eb0b3ae884b6c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.i686-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc4f41ffb8629937d59d8b2c619626f1dbb276e3"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "656d95003a2e47f544ce9eb9f6fe9ad9823bc7e902d3a9a20d1eb0b3ae884b6c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.i686-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a71e380f3645f4f2440e62184b70a8d92c0672bb"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ed39c23d178080b7cce6e4e459194b80615d6e4a67dd04c20ce255297193e2e0"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.i686-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a71e380f3645f4f2440e62184b70a8d92c0672bb"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ed39c23d178080b7cce6e4e459194b80615d6e4a67dd04c20ce255297193e2e0"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.i686-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a71e380f3645f4f2440e62184b70a8d92c0672bb"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ed39c23d178080b7cce6e4e459194b80615d6e4a67dd04c20ce255297193e2e0"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.i686-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c60e5f3bf346af566829c711018b9aaf8cda0e21"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "581f43b9c0689a876ea26bff8d01aed94f796cc478a26f2c9fce89b912f3b0e6"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.i686-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3f3f5394558ffea88b2f0e8a9ab1aed334157b7"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "af32ac01ba6425c7a9e3d1b02b5c1485d479718a900cdc236a2eb1043f231b25"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.i686-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "efa6b1ce494864fda93b463e8968e398f22fddd2"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b73394fb22861d8d52bc1e4bbcd1e38bf2cf54483e5808a7d5002884c9f40593"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.powerpc64le-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "efa6b1ce494864fda93b463e8968e398f22fddd2"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b73394fb22861d8d52bc1e4bbcd1e38bf2cf54483e5808a7d5002884c9f40593"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.powerpc64le-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "efa6b1ce494864fda93b463e8968e398f22fddd2"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b73394fb22861d8d52bc1e4bbcd1e38bf2cf54483e5808a7d5002884c9f40593"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.powerpc64le-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfdba720bbaa91d34c0cab9980919e117a3a538f"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "c62abd782e08870f90a719a4754c5ab3c180b46cd3ac0b394b094636864c3910"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfdba720bbaa91d34c0cab9980919e117a3a538f"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "c62abd782e08870f90a719a4754c5ab3c180b46cd3ac0b394b094636864c3910"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfdba720bbaa91d34c0cab9980919e117a3a538f"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "c62abd782e08870f90a719a4754c5ab3c180b46cd3ac0b394b094636864c3910"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "ad168e31f5695caf97c4caae1816874b70811f4e"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "b43a3e0c628edc365ceb8b60ae1d06feebef6f1d9e8572bf61c00c507646b09d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "ad168e31f5695caf97c4caae1816874b70811f4e"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "b43a3e0c628edc365ceb8b60ae1d06feebef6f1d9e8572bf61c00c507646b09d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "ad168e31f5695caf97c4caae1816874b70811f4e"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "b43a3e0c628edc365ceb8b60ae1d06feebef6f1d9e8572bf61c00c507646b09d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0281662544cd9140aadf471faa55022dd8e8b6ac"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "03be32c12a41b3c1437573b3fdaeeef18914ac40928d8d14dd6e3308010d4357"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.x86_64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0281662544cd9140aadf471faa55022dd8e8b6ac"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "03be32c12a41b3c1437573b3fdaeeef18914ac40928d8d14dd6e3308010d4357"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.x86_64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0281662544cd9140aadf471faa55022dd8e8b6ac"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "03be32c12a41b3c1437573b3fdaeeef18914ac40928d8d14dd6e3308010d4357"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.x86_64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c774baf43723dc260660884c7bfd5be63357a275"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "315a37c3c8efa1e16e7f20e992ba26d7e64f4e867637c9419087815ee2df86df"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c774baf43723dc260660884c7bfd5be63357a275"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "315a37c3c8efa1e16e7f20e992ba26d7e64f4e867637c9419087815ee2df86df"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c774baf43723dc260660884c7bfd5be63357a275"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "315a37c3c8efa1e16e7f20e992ba26d7e64f4e867637c9419087815ee2df86df"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3bfb60894c16d8688a35d321dbd743920abca39d"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "5ca35f6372e45e9a505cbd61c81d9dfb95881996b635e16fd756627e5fa45740"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.x86_64-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7075e3f354b1c9d44bc7c1164e3a713acfbe2d6b"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "607328b5c8492f6ecbd8016b47cd0034a4a7597021f27441b3532d6027af7eef"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.3.2+2/LAMMPS.v2.3.2.x86_64-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
