[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "2fdea34019158dcf26de4b1e91b8585a21c94ef1"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "ff74aeb40386a7e92f29c477b63ff74d88fee5d5fcc5228d28d25996ee6ddd72"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "8302ce228f91683b09fed2ba68f5bf07c49773bb"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "50cb74b70b1d131afd45212aba2ad2100cf2ca4c100d04c95b498d8d1d2de4d9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "d78a92aef56ff89cbe09949c31a966fa1b62ddf1"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "940b170427d233718fb16d84ddbee90cb3d6dbf50ab6b5f756e782ed37e53b10"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b0ece58beaef24fd755e6b7f36ad74ae3caa1cf"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "71e88dbf91db1b68e14ed19ffb1bf320a9cd47dc95d08042580c7bfcccb064ef"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.aarch64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19e846ccf1d5ac591e506c85daecbf3f20d0766f"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0e0b26d297f30f11339191af9efe47d77899ac327ce67338353b3c76180bda1a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.aarch64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1305fbba34152a8e8a645c16f13460c43ed7f095"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "dd9d64fa7f4c622f0cb5cafce6b65077e6b518f82c7a1620f4b61d105b6af4bc"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.aarch64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d35ad3396dfb9287dd5ebfa3d1383b7f8af4b72"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "248c388daaff9ad5d5ceb76b673f78b4236226d95e0f17161ca075b33db38fcd"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13eb0f1abd5c481766ee7f1a8159a053f984c180"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "836a542b401f7640e4a02c9dbd3af8370ddf69649873afd98520ef9b71a75ceb"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a92a086a0426c4aadb59e4a5f585d2848e23ec0"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8450be6b4ca7c776bf9254e16b8c87ef6d34f03e81fb503a4b782d2196b691f9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87d963ede8de717ad4202709ebd44835a1bc1320"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7b73b1e09594057568c5b3c0d32f7c1d725c8ed6bfac3b0eb17ba5b4a3c82d24"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.armv6l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "808e592fa645121fed8b30278e4cde0772847e4e"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "98b1ec10a9503e160cf5094f963955ec1855cd007cedf8e1ebd3ca26634f2b41"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.armv6l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d3ab7f1263da3c9bc4969f5c2e6279840e9e838"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "45ce973f2cbf0f6ef877e725f570d796baa3c303634ac0e843ef85d1b123e3b1"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.armv6l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c43e8078d2e04339cbe3db652fec084dc6c871df"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "04a9881e9c013f4656181c25ffeae66a08fec3558ebc9b9370e0090e163b76f6"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.armv6l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f56cd5694bbf5549822cb24fc604573c9a06f55"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ff1e127cb122a9bcc1f3b55dd8992f91d37f6cf4801a02d1bfa1ffe51832efef"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.armv7l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2074237a9d06d5bbdeff9550f950a6b7bbd3865"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ea2c6885a4cff2653666dd0daa37f7139108b5b3441160ffd145c858242a5e4d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.armv7l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8688be8feda9235a260f62945c20abc6e9632a52"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "362778eda8062faa59437bb44b66d0f182c70378677ca8bb93faf7da9f832110"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.armv7l-linux-gnueabihf-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14cc93b5055bea7cca8e007bb7b972a703bb092f"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "54418a66b3a3692c3345d7e7f25aa9f342b81c08dac5a824f4635569ee7fd20d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.armv7l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f2bf2692bfedb250564e9f98e6e479607f989a4"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "500d52ec3b64939913780877122402ad3b156d7740e7ddae4797921067dbc608"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.armv7l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3c03c1efc832aff5ad31922c3b082726bf41cf5"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "c7a2550ba1c050ac9ff9fc3060fa6686b1b198adf413d83e4c7b293c951f8672"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.armv7l-linux-gnueabihf-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "138fe42ae30c81df02e60de8aee8cba96d3314e0"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "2149b24bff4d533cbcddaf3de35ed81126b65d810af569a2ac57caecab642590"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.i686-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85d4763dbb68266853436f2aeb8fc098fb928f5d"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1ec8ddaf5b2ea389daf68a69c6890263590375cc1d7e32654a70e84c29465ff0"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.i686-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3a7a4b7fe8555528ab6c68116b75286b4f10947"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "54e76882a83e8fc8386b8294d8c2ff125f05d0364206f28c21f9761ea126f47f"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.i686-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad628e8768da7f02bb65bad02714a0c4c2f4c1a8"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "5b48b9952c81e7bac3f28726de8b36ae10345a547f0df065fc576ed36feefde7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.i686-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb58670be37817d0efaabeeffabce42ceb2b1ba6"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "addf2a76509ac1791a0fbe9eaf00730973f6fb30c67c57d237a1fd7b939cce86"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.i686-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7dd9a0ed0bb42087a1aa6869d80b32d78fe07cd8"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0e6412ee1c3bd593516832d9b207fc389088fe046ba7075a1fb31ab70c131e46"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.i686-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69b50fc808f025c0ca0b40fb0512f6c2266f55f7"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "0e3b3438553d660095e70bd4186e50200980b18959d1efd1aa43bb9b20d99c0c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.i686-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a9e1bb2260a65e58723d89e012270af84f336f8"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "f1219cdd805e8c808417bd423c062ba1cebb805cec165e4f969dcefc295bd9eb"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.i686-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c3b187fd43e5f7380fbac7941db3f7174a0ae95"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "62abac6feb78842df6f38fabd383c9fe1196064111920e89810eac7d9f94a9ca"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.powerpc64le-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4896bf2d2b91b976cb0607fa212c456c3a730ae3"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "c96b4b86f384e1d03e3b7a605961056505d261de9b28a0ab8eabfb7f635a7c5d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.powerpc64le-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8d8bd92f404cb8ce1bc1b93be7d44260568a12c"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "f580f1421ae8c58239c003c540f6b5318c8e1868a7aff2c9ea753a5648f5212b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.powerpc64le-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3d4134ec93b3c3d41a030ca35ff9de3a0042f12"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "3435fe47e0bd76dee62a93fcdea9d699afb3656db15fb14311a04bc99859af9c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b228ae050fd1b963a0cf3651dec1f3f715c3c5d2"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "03fe94b3adc5fcae44a384ae0f5d7f66496e51f44be55fcf79c5fc6ad534822a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22c7623853c05a08944384b3ea8f828a5b4a7a43"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "e79b9e0be7a835e8c2f602d6f2551016a39108fbe8451822b3071c797aa1863b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "bb3a9288f6e094d29a4ee42a99b78a470a2be4ea"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "3482faf0484c5ece60db459657c8436f5a02fec2a52133b4aaa495d63734e42b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "34bf857b19c8b0e9385144dec79e1ddee9bdeeff"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "c1fdeb0b00a840a8d410cda75ae8ae4239cd122ac27c358d3f2ef3a6a4488ed2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "c6b7ef5d4eb51b16a3f9708c5aeb5724edb5cf1b"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "d2656babe1615a249aaa302dca7e0c188c8d4ddbc1b81f1798ca9add74724b62"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f44867e4969499b31f3457d4e9770e1a87ba11e4"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1698f541e786c1ce46edf18026859ee9482d137db74a3a4e7b9fe8dca9f9faf7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.x86_64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0b0232052aaf889dae8ad85615d3318e2b3cc25"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "21907238c38c7d5042ffc7992c640008888bc5598f7969e8363914960befb004"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.x86_64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a236375fd5fa273f748e86683709ec5693d99f12"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "c0c4ddc6f9a3c15e170b7d09a779cd390ea2ca0281ee708dd42b0d5b2d630004"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.x86_64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34f3a7a4f1731175f0df7dbd46d54126f1e101a9"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "9e448befe08204c38ecb725728401319688961bbbf4632f24e22f8bfb218f440"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "702c56110576a10c848ade3edfc851d11311b870"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "e5b4ae01d17a79a9d3ce223f05f19eb276fc7a9505f13bd378b88ec93d2fb1bd"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f15dbea50666c9a3f104e85262462a28a558966"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "6cf07eae2467797cae90151b3452724831e17ed0dc8afa08dc8c9108f42decc6"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90ad653aa63788c457f6e5a623dbbcabadff235a"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "ff128146ec039ddc539c42dab0148f34c1c3a3a6d8a49d7ad5d9ca0f768f5879"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.x86_64-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00d7b51eda297e017bb9eed900cf2562cdd3dba2"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "6eae327e6c0223de1ca16130f6676fb34347d6567e159822716c4706f92e91aa"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.0+0/LAMMPS.v2.6.0.x86_64-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
