[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "62a6bdcdf71f3aa66ec031de7bc286fc34a7a43a"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "0a4e1f82575de9de5ca82e0785dcff2c270e696d8b4a59444538eeb38cbd8469"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "62a6bdcdf71f3aa66ec031de7bc286fc34a7a43a"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "0a4e1f82575de9de5ca82e0785dcff2c270e696d8b4a59444538eeb38cbd8469"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "62a6bdcdf71f3aa66ec031de7bc286fc34a7a43a"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "0a4e1f82575de9de5ca82e0785dcff2c270e696d8b4a59444538eeb38cbd8469"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88ca6f9ef4d5a6998130009926bf4e3467e01b1c"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "f016251e4fc60a2a4de272fce87dc81a6dbba71df79a95ec0915aa3c5b94ddc4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.aarch64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88ca6f9ef4d5a6998130009926bf4e3467e01b1c"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "f016251e4fc60a2a4de272fce87dc81a6dbba71df79a95ec0915aa3c5b94ddc4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.aarch64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88ca6f9ef4d5a6998130009926bf4e3467e01b1c"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "f016251e4fc60a2a4de272fce87dc81a6dbba71df79a95ec0915aa3c5b94ddc4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.aarch64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf727c36dc2af49dfb72da89c122c49d48e33b4e"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7fe021d84711adffbaa7bf04e38e47b7dfbc8201276769d00145fe26c4593bd2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf727c36dc2af49dfb72da89c122c49d48e33b4e"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7fe021d84711adffbaa7bf04e38e47b7dfbc8201276769d00145fe26c4593bd2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf727c36dc2af49dfb72da89c122c49d48e33b4e"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7fe021d84711adffbaa7bf04e38e47b7dfbc8201276769d00145fe26c4593bd2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63dafef94b2c7015cef15fa893a9b65ee7f85958"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "d794d2bc8677671be96eb79cabec91c43cc40c55e1632cd01f15867c46c5c2ed"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.armv6l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63dafef94b2c7015cef15fa893a9b65ee7f85958"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "d794d2bc8677671be96eb79cabec91c43cc40c55e1632cd01f15867c46c5c2ed"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.armv6l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57fce4404ac2416b7dfa72c5b74d9f1696794624"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "a9d1ae5fdc01cc111711bd96fd52c64ad3a6462da2ea35f26fb62412490a6198"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.armv6l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57fce4404ac2416b7dfa72c5b74d9f1696794624"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "a9d1ae5fdc01cc111711bd96fd52c64ad3a6462da2ea35f26fb62412490a6198"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.armv6l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11362cac42aa4023c1ab32eaba99b7b01f60428b"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1bdd0d199a9683c5ecbcfab51a2582c88ada0e8e4512ed7576477a56d76a53b1"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.armv7l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11362cac42aa4023c1ab32eaba99b7b01f60428b"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1bdd0d199a9683c5ecbcfab51a2582c88ada0e8e4512ed7576477a56d76a53b1"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.armv7l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11362cac42aa4023c1ab32eaba99b7b01f60428b"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1bdd0d199a9683c5ecbcfab51a2582c88ada0e8e4512ed7576477a56d76a53b1"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.armv7l-linux-gnueabihf-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d17e673e693193f537c635ffc0092ad84042c00"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "64ef03aa93068246afa02ee420267ded4f9b43c0243740d66d74114b5a42cd86"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.armv7l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d17e673e693193f537c635ffc0092ad84042c00"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "64ef03aa93068246afa02ee420267ded4f9b43c0243740d66d74114b5a42cd86"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.armv7l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d17e673e693193f537c635ffc0092ad84042c00"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "64ef03aa93068246afa02ee420267ded4f9b43c0243740d66d74114b5a42cd86"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.armv7l-linux-gnueabihf-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c169996822701572410198397c59afa43ce260a1"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "314d755d941f4ca0788d3bb0e84f9e4b83cc8dd1c53461b854a4b6d6fd9aba2d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.i686-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c169996822701572410198397c59afa43ce260a1"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "314d755d941f4ca0788d3bb0e84f9e4b83cc8dd1c53461b854a4b6d6fd9aba2d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.i686-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c169996822701572410198397c59afa43ce260a1"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "314d755d941f4ca0788d3bb0e84f9e4b83cc8dd1c53461b854a4b6d6fd9aba2d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.i686-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "956ed7311df5a2d11b33f73fa833055dd69f0c89"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "194f3d31b677e7b49cc3a2863d5d35e0ed64dbd061b19836efc1da9fb941e088"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.i686-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "956ed7311df5a2d11b33f73fa833055dd69f0c89"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "194f3d31b677e7b49cc3a2863d5d35e0ed64dbd061b19836efc1da9fb941e088"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.i686-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "956ed7311df5a2d11b33f73fa833055dd69f0c89"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "194f3d31b677e7b49cc3a2863d5d35e0ed64dbd061b19836efc1da9fb941e088"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.i686-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e7999816621bd8477821414d72bdf5187774a1f"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "8ad50bea9a355c532fc90b2f008ff04558cd5237035ccb40a028ba93f5238d93"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.i686-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ddb0088917aa55876e779fef594de8418d24038"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "3dcdb6021878e91707494b145eb41eceac7169ca51f40d2759a9f84601e4b323"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.i686-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f0d2494b0b373308ac34ef422801e8c49269959"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "cd221cfc099d8159fe585c5493e61fd0b5b337d82732681002fccf347bfeafd6"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.powerpc64le-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f0d2494b0b373308ac34ef422801e8c49269959"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "cd221cfc099d8159fe585c5493e61fd0b5b337d82732681002fccf347bfeafd6"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.powerpc64le-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f0d2494b0b373308ac34ef422801e8c49269959"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "cd221cfc099d8159fe585c5493e61fd0b5b337d82732681002fccf347bfeafd6"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.powerpc64le-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67821a208e8923f64c41a554af0ef503b7ced812"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "941224280e0e63dcfdc374c57e10f786183590c484c95a3e3edf810e84783465"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67821a208e8923f64c41a554af0ef503b7ced812"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "941224280e0e63dcfdc374c57e10f786183590c484c95a3e3edf810e84783465"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67821a208e8923f64c41a554af0ef503b7ced812"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "941224280e0e63dcfdc374c57e10f786183590c484c95a3e3edf810e84783465"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "b5642fab507599d8ee05fd5297d26e20340400ea"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "e8b114fc83eb72bae6e3716c5a61860725eb2a7bd0a314b831de997328b880c2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "b5642fab507599d8ee05fd5297d26e20340400ea"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "e8b114fc83eb72bae6e3716c5a61860725eb2a7bd0a314b831de997328b880c2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "b5642fab507599d8ee05fd5297d26e20340400ea"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "e8b114fc83eb72bae6e3716c5a61860725eb2a7bd0a314b831de997328b880c2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce0d4d7c7961b3e94eb68ad2fe13ab43b41df188"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "9d3f053272ac8f01992c52358b71b8006ef9d0d87dc9f22f81cac9c57f2988aa"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.x86_64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce0d4d7c7961b3e94eb68ad2fe13ab43b41df188"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "9d3f053272ac8f01992c52358b71b8006ef9d0d87dc9f22f81cac9c57f2988aa"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.x86_64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce0d4d7c7961b3e94eb68ad2fe13ab43b41df188"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "9d3f053272ac8f01992c52358b71b8006ef9d0d87dc9f22f81cac9c57f2988aa"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.x86_64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "105d41d4726d74349b24b4261e3fc4f7512bf509"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "6a4b0f2afd21b8a3f994cadfcf664ab3cf53c3594b969e98b6fd24fbb69f9827"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "105d41d4726d74349b24b4261e3fc4f7512bf509"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "6a4b0f2afd21b8a3f994cadfcf664ab3cf53c3594b969e98b6fd24fbb69f9827"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "105d41d4726d74349b24b4261e3fc4f7512bf509"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "6a4b0f2afd21b8a3f994cadfcf664ab3cf53c3594b969e98b6fd24fbb69f9827"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95668b4f0b047cedeeb66a2f7212e5cf6ad396ca"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "4c20fb87937584b3440de9479db38e94a269208e2eabae75a96ea8400d492ab8"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.x86_64-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d1c6da596ae8fce6bb6caaa4212575e90070a72"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "58a11e6f170a6389708aea338339c3a9f40c6d3570391dfbf7c8da82240bf5bc"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.4.0+0/LAMMPS.v2.4.0.x86_64-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
