[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "6ff995f3e48ed7e5acd6cf70ce5190c4fdd017e3"
libgfortran_version = "5.0.0"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "ec54f8a67cb271bfa72bcdbb66d3b1b45663fc5e31469c75c96d0ba98e934872"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83347a0d058d83926f027c844af5e93083f3ab0a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8292683a8651e9272c6e8576eca8b5b5f93ad5e7a3cb0b32137695d5c9f996dd"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.aarch64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e40b44a64a1916a1c075909af38950e61aad1853"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fb0d61eeda46c4f09d6bd7960de2a703eac86b870e209732adc5f5e13f24e532"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a241ee216d5c9604efa86410a0fd900b9d8c480"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ca353841ce2c886c0dde4bc49f954dd705ee14b04dd7e368d0c2bd4ae7cf745e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.armv6l-linux-gnueabihf-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4e02b3a0f6b194f8e93032eac31abc39b514ecd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "e5ee4d4d494f8b8f3a720cd968330d22bdbc965f1c915d36b0efe7e0b2aee4a1"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.armv6l-linux-gnueabihf-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2aa52e69f3b1f3353573d9c2f530c815600c369"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "69c7e1a4baa93f3c183e22d637194ed22410cfee7d3e3cf8e7df20277f3e1c01"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.armv6l-linux-gnueabihf-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "857ab055e1f3f90af18dd1baae6338ccfb9d709d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "914b3ede611a5db24bfd636b8323cb3876aa019bc231f7a8900b768021d277a5"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.armv6l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9e7db470a5e02f05cdb4ab487c5e856b23e2f95"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1277ea204415aa5d6aa133aff8f4289070ec655cce10e1ec2863fd659bc74d3d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.armv7l-linux-gnueabihf-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36f4b0ff9e402890cf6c1698cad44e926d541e30"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "bf6b5d3ce34eb4dc8040f1c1d6bbc4e1fea2247e5ed4963edefabdfbf75c4086"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.armv7l-linux-gnueabihf-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cd7012dbd51a1ec14ee70e7264dfaeb8ef17d98"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "6b0f1ff177dd2bdf66791eeaeebfc8ee0e61171e716a2109536ec6df5d4b6885"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.armv7l-linux-gnueabihf-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d452e3ef381e9c5df809715ebfd07fbd6472809a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1a4d3fc49c80c51250fe77607c15640da30904a88c1d4fc83655a06d2e631450"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a3b5be7ffb90b8384f61316e439b80898c2811e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fc0b7cb665f91898deed893bd459e0b64fec11f399e404721cd0b00ca7296275"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.i686-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dedc6f962f972974fdf39b522664756ffc3c29f4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "f944162dba9cc2c38bc9c00e172cb4ac7f5f6667916a3116e0c54c17a8e8e20e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.i686-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f42e280d0e7db577fed63bbe240abadb605509c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "c3f149118ea35f9baee335723b332783941f5724927fb1be5ca7f03a1b74d044"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.i686-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82cdc63095290c4e5311596f322d1112ed80fa60"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fe7562a6d80f9171d9cd57c0827c8d4034d46cc1b9a2ee32aa51a8fb6772ac44"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba938066a5f9b4b66d1a5da9097a42fdf14374f0"
libgfortran_version = "4.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "d50d052de238ce50f41c672f5ac83ff9ae016a5875c3e5572b6c4e40ae0dba7a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.i686-w64-mingw32-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54a949b8c84deb01aab2fea867fa89eb674054f3"
libgfortran_version = "4.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "ceb61ed04bdbc760440c56c0d70a76a9f748c0dec41d87f1e638edd7c133ecc2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.i686-w64-mingw32-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85079241961ed8abac37efcd898b0699de854e82"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "4a3422c412d898c70d52ac8b3bdf1c6a83de975e7f7db69a766510c4b3b913c4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.i686-w64-mingw32-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d81f9b030eb226f3a310b2ab0bc537fedeb9a5f0"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "e31dd1f2c4fad0d9d11d1b133d12551612162f53d164e935f22111672125ec44"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e91b892c8fd16f773f19599b2e1c1749b03c8df6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ad0a83216dd6c7079779b728e0a3a174d2997127d22504d0a2d08e8ab66326bb"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.powerpc64le-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01fd91e152cc91089d7e7cffe779686c2d2201b3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "12565ae668b67bc96a2584b916ae3db249a9e8ce957ac4d1d0a3109a746a0e53"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.powerpc64le-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a596a6482d0baf0ad9603c24f15ddd7ad12b18e7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "cab0f56f5c606afbf167e8a67f2abc0b6e9e62d68ec38e4d277c95c7193697da"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.powerpc64le-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9b21b4f01bdf13dfd99e2792d7e3292fcded659"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "463d502a1b3d769ddb44ef655b37f122b0545c6fa11935df4855df716b481593"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "9b74f5270a6c844091e9b312e3f5a787fd32fc4f"
libgfortran_version = "4.0.0"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "150922cf11bd9adf4403c28995ca02f756834722f6efd4ef7a625c44dc5be908"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "8d0ae37fe644d1adcba00ab33e455cd78e1cb218"
libgfortran_version = "5.0.0"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "c029f0f36587a2b7cf18bdd3c5e415b7adcc8cd604f1cd76f29e8bd6278c9b7b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4749eff8b9bed7f44d68b5a3aa95e2921a9916d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8e2d9a0758ff3b1b9c58a481b712fc84429e12d52089167d7ae3704920386d69"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.x86_64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08e9796d889b1b26f2d85bbca4cd0d2c590cb280"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "2eeb3d85243ad4903f8bac99f4c5fca3074cdfc9c0820a638d47f27295237157"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "733248f11aa3c7b1b1779897baeee164ddda18aa"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7348a48c8ccf6ac6c3c05d379287cb7980afe76bc2ca5fd2c8e278c2d94d25b9"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.x86_64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "044b2f8b2c1224c88867eea9e551997f1952ed8b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "74c1c800f730ebb3d33280d77e798f2b5b8ead3918695abe4a4ad1d5baf17d80"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "428a52031df60d6a3a197522ec3e1d8af9784b30"
libgfortran_version = "4.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "844e21fec047df4814a62afbd83eb2d898a72d0464550c076ebbfe2d153222ae"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.x86_64-w64-mingw32-libgfortran4-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e5acb21013c07941a5928366e492f1e7fde3c75"
libgfortran_version = "4.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "58361aaa4f45d0af7c597c7c977557d934b636eb4d2ca95c3eea426d32c0ce9a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.x86_64-w64-mingw32-libgfortran4-cxx11.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13488e04f1797df9b8aa7b1c7a884b20c6323cf1"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "1aacc7d7e260df51c497e1d2503a7a3851da2a6de78e2383929568888d5e51e5"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.x86_64-w64-mingw32-libgfortran5-cxx03.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9375b3a8e5403c83802b2645a167a7353ea651ac"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "4832713aec17b1b4b0e65426552eeb9e542ea585d2253de5c6762010d021e0c0"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v1.0.1+2/LAMMPS.v1.0.1.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
