[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "57e8086acb449b3a9cfcc842e60edcbf7b3d583a"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "1e4083e988b013d3b1a0813ec3a6b43c25aee7a846dbfd1a607a03f87d6ca8a1"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "19494db62cd5948a95abfcb98da7be5f2b0a2584"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "4b80608d4d4fbaa706bb29630bc675773e338ad303fa0b479fd28aca2b28ce07"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
git-tree-sha1 = "214879636018f1d5f427594471c72f849a310c05"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "5423d32262171f445f517da93428ab9c7d351204f7994675b7bd7e24f675cd48"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "134718577815b39d0fa745344097d5e0f9aac80c"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "f46fbd12d5aa70983fdba19df1b0babe7d634e4bb5e5bf2fdf45dcc32f278ab2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.aarch64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b5d5552ab001446f6deb2c4a7d0f13018e26220a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8097f673d7feb5f5557b1561bc5c5620bac05ace41c1b0246d38b0f19a44456f"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.aarch64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de1ee958f47d12d059a666b63ccd767941292be0"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "b1684cb89628694616fcbcf1a9fca8ebb250304e80f32b1cc8e6db18a89a7d63"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.aarch64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88d2d8802f22cb427f5dfe0cfa5bd6db4312493e"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "5c77ef736f4710f1ac7c430c6b4fd7ec23e350d335a2c7ab8c7665fd70d7caf0"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9934181e648bb6a6a49b33bb245b95003687abea"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0b37021f18e25fc07d83b80d56eac9339ab252d8d1b8973a83b3f67ae159dfb0"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d15ab88d0f2cdff5c8e60c9baaa685c956010fdd"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "1947a1a054b88f153e4abb948f7a9ebc599a6400f9278b4d214654417dfc8aa4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "978e164e0a6d97176a0a9eb21d8ec225b0cf73f5"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "76d734f8eed55b9761de00e23e5009270faa45b0834e471c456992b7b968166e"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.armv6l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e01a7a5488689e5589d035e5bbbb87f08c8d931d"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "2cff1ba88a67fe88ae10e26273c571e7812a6542ee850a7d969445d82ce64c79"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.armv6l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8beb783791a12b187340c8a0995f6a3b9047ee36"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "8844a64e5a1a838f023f03ac02f8dc0e942461ae28578702ccb6fada998e6f66"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.armv6l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c58ed01b7d56ab9b4b7117db9433bc2634c1a0d"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "57376af3e6b90a83b35a3a522a3a1fc87172debc9e82e25ff052e7f0a1b5ee08"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.armv6l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0788f66df22805436f715e8cbe5af1fbb4a40de4"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "c3828b983c39c49866a561877d7ceb71ff0a8ece2fe478ba612e9f2bf4ce8677"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.armv7l-linux-gnueabihf-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9adb8cec3ebc7f406eb723923fb5afd2d7a8dc3a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "40582ca5b4bbbf9bb48f9cf5eac7dd1d6bb231a14015391e4c4c7a8aa8300f3c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.armv7l-linux-gnueabihf-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cbce1cf20667cd973ca59efa05ef45dd357d547"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ffe9609c2042026fc145fc221dbecfb7850e3e5101013d51798cc0bf511f202f"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.armv7l-linux-gnueabihf-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "682971561cc4b06dc3a79106c33912a52e011232"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "4f77174aa3c36275314514fab1646e08073dbcb6f07a91b69326b1dcf29eff00"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.armv7l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e39fdc1e5305b29bf34c9aa009254734b4f4c21"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "a1cb3fe6399b3d10e127032ec6441ff309290f4811c4ea9c36f3d351bdccccea"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.armv7l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19bc99bfb75fdbd97aea94a481ce0b0de7f1fdcf"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "a1d6b1a22e70bd8e0dc4957d6a4d10e85f68cc7f37c95d3e10c41fbef49f952a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.armv7l-linux-gnueabihf-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d224558505899cb8ee6de9345ad03b94cdf51fcb"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "c92a7f638f7f05a8801c216508a21b1dfb36cc7d75da92c9ec37bafb6706fe0b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.i686-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77a854dd2ccdc59d38fdb4606f964a533c55f483"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "f502ee2f28d1c673b37921341ac3d198c79a4b1b94df20313da85d8bac8ce604"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.i686-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f424e0d89c80d7fe1926cafa9c7917046840673"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "fe64c5e9d9980005772e8f9d4d5634e5f0fb9837d48043c7df56d0c79dcc1c9b"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.i686-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0712e141b62e5c28e5afcb3b506a4b3f80d10871"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "76a1193bf69604d676f1942711ba793451b02b9342e63f1b08d20f03025228d3"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.i686-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8572315730434a66a3d154f0facd7281cfb89c15"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "a4afa2e0fabfa7c1bcc45fd3cff71dbcac24025f4aeac8c66620f384383892d0"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.i686-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbb44b2783c980b1f0b7b2b70a092c38ce2b6a20"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "439d89f5248759d737c1aa3c99a0f8a9f4ea3ba9d0d86e63233579d84d08b2c7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.i686-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93d3a27cc5d1fbeda556b1a0baf42022b7f6d4c6"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "38b0b93d11ae723299c14bc333cd994ed7f06ecc0357c66b5e40c77882ee2a47"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.i686-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fb37689006015f5a00354f81c3fefd837e5809f"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "71c50935f67ae6a59398f46a29192e6789795a675d22a4913f76eaaeb84f040f"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.i686-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5385a3c685b7d942b7b95f6fe6634dcbcba644a8"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "653984d74fdd3995c4c7c60f076cdce34025a1adcd8264950fa11a5210debd5a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.powerpc64le-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c56f07ac2d6a8d8c4f0f1a4a38eaa8c93562ce89"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "98a984067de87b9071e2bc63f398a5e4399de9f7903eac3f63b74a5c12f1de4c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.powerpc64le-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73b67f4455c2166e4dc5df63e6c75db342c5affc"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "063215d8027c7071d737c3fb9d6b29d421a265d16d2cadd0c9e02cc10f64af4a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.powerpc64le-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "006f6f5ecbb47695c80ab9ea4803780edc5fb853"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ecd60a9b48c06d16d3199394fab18c25ff5e3cb059d4682bb065b7933fdfad42"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1f5cc8c78c8795f5c52b55dc7b5ec551ea2b8e4"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "a779c69a6b050b378c241326e77b0503f426cc2df7a59f9e180b222ad9de910a"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4370687ddd7bac1516eb4ee60844859a808a4ea"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "cd18b2f2469d11f4161d2234e08e3258158d0c35f16b61040db9b604e4c63bad"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "05bd11638a7a5dd44eec98318e62c87331f41e5d"
lazy = true
mpi = "mpich"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "d3e53f2f3a7218d1fd184befc46fb44a0fc342859bbb1177bee008cf82ca3a50"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "54cc2ea675b8ce0797e409954b9552844b87d275"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "93e6ec67c97dace30e17fe710ba66596a431302c9c99b2201aff845de0ca3e7d"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
git-tree-sha1 = "7fa9c31926711411dd6219f19670a11224691943"
lazy = true
mpi = "openmpi"
os = "macos"

    [[LAMMPS.download]]
    sha256 = "6059a41085170e29e604c5b1eb09d473479e3baecebefcbae759e4d2d0f3b03c"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d746f54ea366075ae10ca5f791d728e6aec9354"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "0379293cb321cdd74170e7742b4db8aee90421dd7b1588a10a0a8ecead6a24f2"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.x86_64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c1cb4911b6b93b64fb781f559bb2d4d4693dd91"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "5d11107f5b1bf3c70a7bd2c3a97e7441a76444c6c6d987fb3dcbbd28187985d7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.x86_64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3071fd123c9a987f082c2c796f77cb2b90cd4ad"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "7a9d727f80cadfc6783a6320d2952dbf1c72c34d5541d81e95709158835754f7"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.x86_64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae8b913bf6ace4e16a325ef55d3d80a763edb59d"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "2bc22927237bada442f14bcb0ebe24a6922200e1e2d4f6016104f54a26b3f6c4"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "123527406dde5a5df9db7955787a83380a88a497"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "98845be5dee46fa2f449261610828e6f7fc2ea3b91df84b03b113b77fa3abb51"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfdcd261023503497fde74bcfb29266ba289b3bb"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[LAMMPS.download]]
    sha256 = "ae522070ca43cc3739de1d3ec37d01e9ca1cd9191e7f860de1439b10afb83dff"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6d1d2aee73a0459587e8f3566f21c92f2808f7d"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "642ecdb48a895101f6e630c42e90282d48f6a6c1bd6c830106db3bdf6ba5a925"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.x86_64-w64-mingw32-cxx03-mpi+microsoftmpi.tar.gz"
[[LAMMPS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1574e25b5bd701ede3e29727da9503b88b284090"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[LAMMPS.download]]
    sha256 = "efd49f0df0ec276c0967d7af337ccd5c2e97e5d06b616b8fd1d6f38aaef91c39"
    url = "https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/releases/download/LAMMPS-v2.6.1+0/LAMMPS.v2.6.1.x86_64-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
